# permissions for end users to view managedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: managedsecret
    app.kubernetes.io/part-of: managedsecret
    app.kubernetes.io/managed-by: kustomize
  name: managedsecret-viewer-role
rules:
- apiGroups:
  - webapp.test.com
  resources:
  - managedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.test.com
  resources:
  - managedsecrets/status
  verbs:
  - get
